apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf

      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter
        ports:
          - containerPort: 9113
        args:
          - "--nginx.scrape-uri=http://localhost:80/status"
          - "--web.listen-address=0.0.0.0:9113"

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
