apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-server
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
